# Generated by Django 5.2.3 on 2025-06-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Chemical Name (रसायनाचे नाव)')),
                ('chemical_type', models.CharField(choices=[('PST', 'Pesticide (कीटकनाशक)'), ('FNG', 'Fungicide (फफूंदनाशक)'), ('HRB', 'Herbicide (तणनाशक)')], max_length=3)),
                ('appearance', models.TextField(verbose_name='Appearance (देखावा)')),
                ('toxicity', models.CharField(choices=[('H', 'High (उच्च)'), ('M', 'Medium (मध्यम)'), ('L', 'Low (कमी)')], max_length=1)),
                ('trade_names', models.TextField(verbose_name='Trade Names (ब्रँड नावे)')),
                ('suitable_crops', models.TextField(verbose_name='Suitable Crops (योग्य पिके)')),
                ('quantity_per_hectare', models.CharField(max_length=50, verbose_name='Quantity per Hectare (प्रति हेक्टर प्रमाण)')),
                ('quantity_of_water', models.CharField(max_length=50, verbose_name='Quantity of Water (पाण्याचे प्रमाण)')),
                ('usage_notes', models.TextField(verbose_name='Usage Notes (वापर सूचना)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity (स्टॉक प्रमाण)')),
            ],
        ),
    ]
